name: Train Pac-Man AI Model

on:
  push:
    branches:
      - master  # Now tracking 'master' instead of 'main' or 'brain'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master  # Ensure the workflow pulls the 'master' branch

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Models
        run: |
          python main_train.py

      - name: Upload Trained Models
        uses: actions/upload-artifact@v3
        with:
          name: pacman_trained_models
          path: trained_models/
